name: Deploy

on:
  push:
    branches:
      - main
      - 'release_*'
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    uses: ./.github/workflows/_build-and-deploy.yaml
    secrets: inherit
